# Generated by Django 5.2.6 on 2025-09-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('spotify_access_token', models.TextField(blank=True, null=True)),
                ('spotify_refresh_token', models.TextField(blank=True, null=True)),
                ('spotify_token_expires', models.DateTimeField(blank=True, null=True)),
                ('spotify_user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist_id', models.CharField(max_length=128)),
                ('artist_name', models.CharField(max_length=255)),
                ('song_id', models.CharField(max_length=128)),
                ('song_title', models.CharField(max_length=255)),
                ('song_popularity', models.IntegerField(default=0)),
                ('vibe_sequence', models.IntegerField(blank=True, null=True)),
                ('playlist_sequence', models.IntegerField(blank=True, null=True)),
                ('playlist_hist_sequence', models.IntegerField(blank=True, null=True)),
                ('is_playing', models.BooleanField(default=False)),
                ('is_played', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
    ]
